### ISSUE TITLE
The game's unplayable.

### ISSUE THREAD

**Issue by cedric-h** [igameproject/line-ball#12]
Don't get me wrong: I have nothing against hard games. Actually, the opposite is likely true, as I'm a fan of _really_ hard games, like Super Meat Boy. But currently, the game is so hard as to border upon the impossible. I'd like to refactor it a little bit: make it full screen, maybe add some better physics with a ground and a side scrolling that only follows the player. Also, I want to give the little ball a shotgun with a ridiculous recoil that can be operated by point and click, and have him use the shotgun as his method of propelling himself. I think I'm more than capable of doing this, see my main project: www.substandardstudios.github.io/gdi

But most of all, I want whatever code I write for this project to be useful enough to be merged with the main distro, so reign me in if my ideas are too much. Lemme know which of the things listed above would _roll_ (haha, get it? he's a ball... roll... hehehe...) with what you all have planned for the game.

**Comment by cedric-h** [comment]
'Til then I'll fix the other open issue.

**Comment by cedric-h** [comment]
I made a shotgun based upon the games current art style. 
![shotgun](https://user-images.githubusercontent.com/25539554/31412677-0826d0d0-ade4-11e7-80f1-89a53b6a03f1.png)

**Comment by VRamazing** [comment]
@DefecateRainbows I think I like the way the game is at the current stage.If you want to make it more playable.You can work on that.I am not a big fan of the shotgun idea

**Comment by cedric-h** [comment]
Alright, no shotgun. That's fine.  I'll make it more playable, gotcha. So far I've set up fullscreen, and I've started working on scaling the height of the pipes to the size of the screen.

**Comment by cedric-h** [comment]
#14 Alright, here's what I have. I'll stick powerups in here later...
Just saying, the shotgun, and things like grappling hooks, hang gliders, jet packs and chandeliers(don't ask) could all be powerups...
Ooo, and poles you could use for pole vaulting off of the pipes.

**Comment by VRamazing** [comment]
@DefecateRainbows Close the issue if you are satisfied with the result
