### ISSUE TITLE
Add lives to the ball

### ISSUE THREAD

**Issue by VRamazing** [igameproject/line-ball#2]

**Comment by Charlie43** [comment]
Can I work on this issue? :)

**Comment by VRamazing** [comment]
Sure Make sure everytime user strikes the line his position reinitiates to the center of canvas height and lives reduce by 1.Also make sure user can see their current lives on screen

**Comment by Jake0Tron** [comment]
I've implemented lives on this, was planning on pushing it up tomorrow for hacktoberfest

**Comment by VRamazing** [comment]
@Jake0Tron  You can always participate in new issues or give your own ideas on what we can implement.
